"""Initial migration.

Revision ID: 0beb92b26f01
Revises: 
Create Date: 2024-06-09 10:56:13.510804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beb92b26f01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_student')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('picture', sa.String(length=100), nullable=True))
        batch_op.drop_column('fee_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_paid', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('picture')
        batch_op.drop_column('fee')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    op.create_table('_alembic_tmp_student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fee', sa.FLOAT(), nullable=False),
    sa.Column('picture', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
